### ISSUE TITLE
Server Crashes on start up when attempting to use this mod on a dedicated server

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [pitbox46/MusicController#1]
Music Controller Version: 1.1.0
Forge Version: 36.1.13
Crash Report: https://pastebin.com/QXw8EfQG
Latest Log: https://pastebin.com/QebNb4TD

Whenever I try to use this mod on my dedicated server, the server just crashes on start up whenever I try to run the server with this mod installed on it.

I have a feeling this mod is probably a client side only mod but I thought I'd report this anyway in case it isn't actually supposed to crash the server.

**Comment by pitbox46** [comment]
Should be fixed with latest commit and Curseforge release
